### ISSUE TITLE
Main task list 

### ISSUE THREAD

**Issue by SMEasterbrook** [SMEasterbrook/Arrhenius#1]
# Data preparation
- [ ] Can we get hold of Very's observational data on infra-red emitted from the moon?
- [ ] Can we get the original 19th Century temperature data that Arrhenius used?
- [ ] Download Berkeley Earth temperature data and re-grid to Arrhenius's grid.
- [ ] Explore what modern absorption data is available
- [ ] Decide on data formats for input data (eg. NetCDF)

# Coding tasks
- [ ] Calibration step to calculate model constants
- [ ] Build the main control loop to run the model
- [ ] Calculation for single grid point for given absorption coefficients
- [ ] Calculation for change in humidity (one step feedback loop)
- [ ] Write control code for setting up different experiments
- [ ] Write code to configure the models as an n-layer model

# Test Harness
- [ ] Write test stubs for units testing
- [ ] Basic test of the model with Arrhenius 19thC data

# Website
 - [ ] Set up basic website to describe the project
 - [ ] Figure out how to embed a runnable model in the website
